from collections.abc import Sequence
from enum import Enum
from os import PathLike
from typing import ClassVar, overload
from typing_extensions import Annotated, Buffer, Literal, Protocol

class SupportsRead(Protocol):
    def read(self, n: int | None = ..., /) -> Buffer: ...

class SupportsSeek(Protocol):
    def seek(self, offset: int, whence: int = ..., /) -> int: ...

class SupportsTell(Protocol):
    def tell(self) -> int: ...

class SupportsWrite(Protocol):
    def write(self, data: Buffer, /) -> int: ...

class ReadableFileLike(SupportsRead, SupportsSeek, SupportsTell, Protocol): ...
class WritableFileLike(ReadableFileLike, SupportsWrite, Protocol): ...

class PixelEngine:

    class BlockHeader:
        coordinate: list[int]
        template_id: int
        offset: int
        size: int
    
    class BlockHeaderTemplate:
        bits_allocated: int
        bits_stored: int
        high_bit: int
        samples_per_pixel: int
        compressor_id: str
        dimensions_in_block: list[int]
        dimension_ranges: list[PixelEngine.DimensionRange]

    class BufferType(Enum):
        LUMINANCE = int
        RGB = int
        RGBA = int

    class ClusterBlockHeader:
        coordinate: list[int]
        template_id: int

    class ClusterHeader:
        coordinate: list[int]
        block_offsets: list[int]
        block_sizes: list[int]
        template_id: int
        offset: int
        size: int

    class ClusterHeaderTemplate:
        dimensions_in_cluster: list[int]
        block_headers: list[PixelEngine.ClusterBlockHeader]
        dimension_ranges: list[PixelEngine.DimensionRange]

    class CompressionParameters:
        ...

    class DataEnvelopes:
        def __eq__(self, other: PixelEngine.DataEnvelopes) -> bool: ...
        def as_extreme_vertices_model(
            self,
        ) -> list[tuple[list[int], list[list[int]]]]: ...
        def as_rectangles(self) -> list[list[int]]: ...

    class DimensionRange:
        begin: int
        increment: int
        end: int

        def __init__(self, begin, increment, end) -> None: ...

    class DisplayView(PixelEngine.SourceView):
        color_correction_black_point: float
        color_correction_gamma: float
        color_correction_white_point: float
        color_gain: float
        contrast_clip_limit: float
        sharpness: float

    class FilterHandle:
        def name(self) -> str: ...
        def supported_parameters(self) -> list[str]: ...

    class ISyntaxFacade:
        acquisition_datetime: str
        barcode: str
        date_of_last_calibration: list[str]
        derivation_description: str
        device_serial_number: str
        manufacturer: str
        model_name: str
        scanner_calibration_status: str
        scanner_operator_id: str
        scanner_rack_number: int
        scanner_rack_priority: int
        scanner_slot_number: int
        software_versions: list[str]
        time_of_last_calibration: list[str]

        @overload
        def __getitem__(self, index: int) -> PixelEngine.SubImage: ...
        @overload
        def __getitem__(self, type: str) -> PixelEngine.SubImage: ...
        def close(self) -> int: ...
        @overload
        def open(
            self,
            url: str | bytes | PathLike[str] | PathLike[bytes],
            container_name: Literal["", "caching-ficom", "dicom", "ficom", "legacy", "s3"] = "",
            mode: Literal["r", "w"] = "r",
            cache_name: str = "",
        ) -> None: ...
        @overload
        def open(
            self,
            stream: ReadableFileLike | WritableFileLike,
            container_name: Literal["", "caching-ficom", "dicom", "ficom", "legacy", "s3"] = "",
            mode: Literal["r"] = ...,
            cache_name: str = "",
        ) -> None: ...
        @overload
        def open(
            self,
            stream: WritableFileLike,
            container_name: Literal["", "caching-ficom", "dicom", "ficom", "legacy", "s3"] = "",
            mode: Literal["w"] = ...,
            cache_name: str = "",
        ) -> None: ...
        @property
        def id(self) -> str: ...
        @property
        def is_hamamatsu(self) -> bool: ...
        @property
        def is_UFS(self) -> bool: ...
        @property
        def is_UFSb(self) -> bool: ...
        @property
        def is_UVS(self) -> bool: ...
        @property
        def is_philips(self) -> bool: ...
        @property
        def isyntax_file_version(self) -> str: ...
        @property
        def num_images(self) -> int: ...

    class Level:
        def chain_source_view(
            self, view: PixelEngine.View, x_shift: int, y_shift: int, level_shift: int
        ) -> None: ...
        def filter_width(
            self, coord: list[int], dimensions: list[int], filter_kernel_half_width: int
        ) -> list[Annotated[list[int], 2]]: ...

    class Region:
        def __eq__(self, other: PixelEngine.Region) -> bool: ...
        def __ge__(self, other: PixelEngine.Region) -> bool: ...
        def __gt__(self, other: PixelEngine.Region) -> bool: ...
        def __hash__(self) -> int: ...
        def __le__(self, other: PixelEngine.Region) -> bool: ...
        def __lt__(self, other: PixelEngine.Region) -> bool: ...
        def draw(self, target: int = 0) -> None: ...
        def get(self, buffer: Buffer) -> int: ...
        @property
        def range(self) -> list[int]: ...
        @property
        def ready(self) -> bool: ...

    class SourceView(PixelEngine.View):
        def load_default_parameters(self) -> None: ...
        def truncation(
            self, enabled: bool, rounding: bool, trunc_levels: dict[int, list[int]]
        ) -> None: ...

    class SubImage:
        color_linearity: str
        icc_profile: str
        lossy_image_compression: str
        lossy_image_compression_method: str
        lossy_image_compression_ratio: float

        def add_view(self) -> PixelEngine.UserView: ...
        def block_coordinate(self, block_index: int) -> list[int]: ...
        def block_index(self, block_coordinate: list[int]) -> int: ...
        def block_pos(self, block_ind: int) -> list[int]: ...
        def block_size(self, template_id: int = 0) -> list[int]: ...
        def header(self) -> PixelEngine.SubImageHeader: ...
        def include_input_region(self, pos: list[int], size: list[int], level: int) -> None: ...
        def ordered_block_coordinates(self) -> list[list[int]]: ...
        def preallocate_pixels(self, pos: list[int], size: list[int], level: int) -> None: ...
        def put_block(self, buffer: Buffer) -> None: ...
        def read_block(self, buffer: Buffer) -> int: ...
        @property
        def colorspace_transform(self) -> str: ...
        @property
        def compressor(self) -> str: ...
        @property
        def display_view(self) -> PixelEngine.DisplayView: ...
        @property
        def has_display_view(self) -> bool: ...
        @property
        def icc_matrix(self) -> Annotated[list[float], 9]: ...
        @property
        def image_data(self) -> memoryview: ...
        @image_data.setter
        def image_data(self, data: Buffer) -> None: ...
        @property
        def image_type(self) -> str: ...
        @property
        def num_tiles(self) -> int: ...
        @property
        def pixel_transform(self) -> str: ...
        @property
        def quality(self) -> int: ...
        @property
        def quality_preset(self) -> str: ...
        @property
        def source_view(self) -> PixelEngine.SourceView: ...

    class SecondaryCaptureCompressionParametersBuilder:
        def __init__(self, image_type: str, width: int, height: int) -> None: ...
        def with_origin(self, origin: list[float]) -> PixelEngine.SecondaryCaptureCompressionParametersBuilder: ...
        def with_scale(self, scale: list[float]) -> PixelEngine.SecondaryCaptureCompressionParametersBuilder: ...
        def build(self) -> PixelEngine.CompressionParameters: ...

    class SubImageHeader:
        cluster_header_templates: list[PixelEngine.ClusterHeaderTemplate]
        cluster_sequence: list[int]
        block_header_templates: list[PixelEngine.BlockHeaderTemplate]
        block_headers: list[PixelEngine.BlockHeader]
        cluster_headers: list[PixelEngine.ClusterHeader]

    class UserView(PixelEngine.View):
        def add_filter(self, filter_name: str) -> PixelEngine.FilterHandle: ...
        def filter_parameter_double(self, filter: PixelEngine.FilterHandle, name: str, value: float) -> None: ...
        def filter_parameter_matrix3x3(self, filter: PixelEngine.FilterHandle, name: str, value: Annotated[Sequence[float], 9]) -> None: ...

    class View:
        def __getitem__(self, level: int) -> PixelEngine.Level: ...
        def add_user_view(self) -> PixelEngine.UserView: ...
        def chain_source_view(
            self, view: PixelEngine.View, x_shift: int, y_shift: int, level_shift: int
        ) -> None: ...
        def data_envelopes(self, level: int) -> PixelEngine.DataEnvelopes: ...
        def dimension_ranges(self, level: int) -> list[Annotated[list[int], 3]]: ...
        @overload
        def request_regions(
            self,
            regions: list[list[int]],
            enable_async_rendering: bool = True,
            background_color: list[int] = [0, 0, 0],
            buffer_type: PixelEngine.BufferType = ...,
        ) -> list[PixelEngine.Region]: ...
        @overload
        def request_regions(
            self,
            regions: list[list[int]],
            data_envelopes: PixelEngine.DataEnvelopes,
            enable_async_rendering: bool = True,
            background_color: list[int] = [0, 0, 0],
            buffer_type: PixelEngine.BufferType = ...,
        ) -> list[PixelEngine.Region]: ...
        @property
        def bits_allocated(self) -> int: ...
        @property
        def bits_stored(self) -> int: ...
        @property
        def dimension_discrete_values(self) -> list[list[str]]: ...
        @property
        def dimension_names(self) -> list[str]: ...
        @property
        def dimension_types(self) -> list[str]: ...
        @property
        def dimension_units(self) -> list[str]: ...
        @property
        def high_bit(self) -> int: ...
        @property
        def id(self) -> int: ...
        @property
        def num_derived_levels(self) -> int: ...
        @property
        def origin(self) -> list[float]: ...
        @property
        def pixel_representation(self) -> int: ...
        @property
        def pixel_size(self) -> list[int]: ...
        @property
        def planar_configuration(self) -> int: ...
        @property
        def samples_per_pixel(self) -> int: ...
        @property
        def scale(self) -> list[float]: ...

    class WSICompressionParametersBuilder:
        def __init__(self, size: list[int]) -> None: ...
        def with_num_derived_levels(self, num_levels: int) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_block_size(self, block_size: str) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_pixel_transform(self, pixel_transform: str) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_compressor(self, compressor: str) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_colorspace_transform(self, colorspace_transform: str) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_bit_depth(self, bit_depth: int) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_num_threads(self, num_threads: int) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_default_color_intensity(self, default_color_intensity: int) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_quality_preset(self, quality: str) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_quality(self, quality: int) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_origin(self, origin: list[float]) -> PixelEngine.WSICompressionParametersBuilder: ...
        def with_scale(self, scale: list[float]) -> PixelEngine.WSICompressionParametersBuilder: ...
        def build(self) -> PixelEngine.CompressionParameters: ...

    version: ClassVar[str]
    certificates: str
    network_timeout: int
    rate_limiting: bool

    def __getitem__(self, name: str) -> PixelEngine.ISyntaxFacade: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, render_backend: RenderBackend, render_context: RenderContext
    ) -> None: ...
    def block_sizes(self, pixel_transform: str) -> list[str]: ...
    def clear_render_buffers(self) -> None: ...
    def clear_render_cache(self) -> None: ...
    def clear_render_target(self, color: list[int], target: int = 0) -> None: ...
    def colorspace_transforms(self) -> list[str]: ...
    def compressors(self) -> list[str]: ...
    def container_version(self, container: str) -> str: ...
    def containers(self) -> list[str]: ...
    def pixel_transforms(self) -> list[str]: ...
    def quality_presets(self) -> list[str]: ...
    def supported_filters(self) -> list[str]: ...
    def wait_all(self, regions: list[PixelEngine.Region]) -> None: ...
    @overload
    def wait_any(self) -> list[PixelEngine.Region]: ...
    @overload
    def wait_any(
        self, regions: list[PixelEngine.Region]
    ) -> list[PixelEngine.Region]: ...
    @property
    def client_certificates(
        self,
    ) -> Annotated[list[str], 3]: ...
    @client_certificates.setter
    def client_certificates(self, certs: Annotated[Sequence[str], 3]) -> None: ...

class RenderBackend:
    class ImageFormatType(Enum):
        LUMINANCE = int
        RGB = int
        RGBA = int
        UNDEFINED_FORMAT = int

class RenderContext:
    def __init__(self) -> None: ...
    @property
    def height(self) -> int: ...
    @property
    def width(self) -> int: ...
